export { default as LoginMobile } from './Login'
export { default as HomeMobile } from './Home'
export { default as CommitsMobile } from './Commits'
export { default as IssuesMobile } from './Issues'
export { default as SettingsMobile } from './Settings'
export { default as ReposMobile } from './Repos'
export { default as TodoMobile } from './Todo'
